language: c
install:
    - sudo apt-get update
    - sudo apt-get -y install libtool pkg-config libexpat1-dev libxml2-dev libssl-dev libc-ares-dev
before_script:
    - ./bootstrap.sh
script:
    - ./configure ${CONFIGURE_OPT} CFLAGS="-Werror" && make && make check
env:
    - CONFIGURE_OPT="--without-libxml2"
    - CONFIGURE_OPT="--with-libxml2"
    - CONFIGURE_OPT="--disable-tls"
    - CONFIGURE_OPT="--enable-cares"
matrix:
    fast_finish: true
